Name: TicTacToe
Properties:
 -
  Name: currentPlayer
  Type: Player
  Kind: Accessible
 -
  Name: x
  Type: Integer
  Kind: Internal
  Constraints:
    - min: 0
    - max: 2
 -
  Name: y
  Type: Integer
  Kind: Internal
  Constraints:
    - min: 0
    - max: 2
 -
  Name: player1
  Type: Player
 -
  Name: player2
  Type: Player
 -
  Name: grid
  Type: Grid

Actions:
  -
   Name: PlayATurn
  -
   Name: Draw
  -
   Name: Winner


